name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - renovate.json
      - .github/workflows/release.yaml
      - README.md
      - LICENSE
      - .gitignore
      - config.yaml.example
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run fmt
      run: make fmt

    - name: Run vet
      run: make vet

    - name: Run tests
      run: make test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./cover.out
        flags: unittests
        name: codecov-umbrella

  lint-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Lint Helm chart
      run: make helm-lint

    - name: Template Helm chart
      run: make helm-template

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: false
        tags: test-image:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
